# Generated by Django 5.1.2 on 2025-01-09 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
